export const ourTeamData = [
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
  {
    name: "ourTeamMemberName",
    position: "ourTeamMemberPosition",
    image: "/assets/user.png",
    phone: "+1234567891",
    email: "bob@example.com",
    whatsapp: "+1234567891",
  },
];
